services:
  vortex_db:
    image: postgres:16
    container_name: vortex_primary_db
    restart: always
    environment:
      POSTGRES_USER: vortex_user
      POSTGRES_PASSWORD: vortex_password
      POSTGRES_DB: vortex_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres 
      -c shared_preload_libraries=pg_stat_statements 
      -c pg_stat_statements.track=all 
      -c pg_stat_statements.max=10000