services:
  vortex_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vortex_primary_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VortexPassword123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mssql_data: